-- MySQL Script generated by MySQL Workbench
-- 04/27/16 19:40:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ajax
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ajax` ;

-- -----------------------------------------------------
-- Schema ajax
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ajax` DEFAULT CHARACTER SET latin1 ;
USE `ajax` ;

-- -----------------------------------------------------
-- Table `ajax`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ajax`.`user` ;

CREATE TABLE IF NOT EXISTS `ajax`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(200) NOT NULL,
  `password_hash` VARCHAR(200) NOT NULL,
  `auth_key` VARCHAR(150) NULL,
  `access_token` VARCHAR(150) NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ajax`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ajax`.`group` ;

CREATE TABLE IF NOT EXISTS `ajax`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tutor_id` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tutor_id_idx` (`tutor_id` ASC),
  CONSTRAINT `fk_tutor_id`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `ajax`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ajax`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ajax`.`files` ;

CREATE TABLE IF NOT EXISTS `ajax`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NULL,
  `path` VARCHAR(200) NOT NULL,
  `group_id` INT NULL,
  `show_all` INT NOT NULL,
  `type` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `group_id_idx` (`group_id` ASC),
  CONSTRAINT `fk_files_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `ajax`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ajax`.`assign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ajax`.`assign` ;

CREATE TABLE IF NOT EXISTS `ajax`.`assign` (
  `student_id` INT NULL,
  `group_id` INT NULL,
  INDEX `group_id_idx` (`group_id` ASC),
  INDEX `fk_student_id_idx` (`student_id` ASC),
  CONSTRAINT `fk_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `ajax`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assign_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `ajax`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ajax`.`auth_rule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ajax`.`auth_rule` ;

CREATE TABLE IF NOT EXISTS `ajax`.`auth_rule` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `data` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ajax`.`auth_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ajax`.`auth_item` ;

CREATE TABLE IF NOT EXISTS `ajax`.`auth_item` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `type` INT(11) NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `rule_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `data` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `rule_name` (`rule_name` ASC),
  INDEX `idx-auth_item-type` (`type` ASC),
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `ajax`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ajax`.`auth_assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ajax`.`auth_assignment` ;

CREATE TABLE IF NOT EXISTS `ajax`.`auth_assignment` (
  `item_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `user_id` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`item_name`, `user_id`),
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `ajax`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ajax`.`auth_item_child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ajax`.`auth_item_child` ;

CREATE TABLE IF NOT EXISTS `ajax`.`auth_item_child` (
  `parent` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `child` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `ajax`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `ajax`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ajax`.`migration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ajax`.`migration` ;

CREATE TABLE IF NOT EXISTS `ajax`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
